In [1]:
import gym

env = gym.make('CartPole-v0')
env.reset()
random_episodes = 0
reward_sum = 0
while random_episodes < 10:
    env.render()
    action = env.action_space.sample()
    observation, reward, done, _ = env.step(action)
    print(observation, reward, done)
    reward_sum += reward
    if done:
        random_episodes += 1
        print("Reward for this episode was:", reward_sum)
        reward_sum = 0
        env.reset()


WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
[-0.02917765 -0.15500211 -0.02892196  0.25492318] 1.0 False
[-0.03227769  0.0405206  -0.0238235  -0.04674009] 1.0 False
[-0.03146728  0.23597592 -0.0247583  -0.34684332] 1.0 False
[-0.02674776  0.04121472 -0.03169516 -0.06206925] 1.0 False
[-0.02592346  0.23677643 -0.03293655 -0.36458131] 1.0 False
[-0.02118793  0.43235061 -0.04022818 -0.66746506] 1.0 False
[-0.01254092  0.62800824 -0.05357748 -0.97253795] 1.0 False
[ 1.92430600e-05  8.23806596e-01 -7.30282364e-02 -1.28155830e+00] 1.0 False
[ 0.01649537  1.01977891 -0.0986594  -1.59618448] 1.0 False
[ 0.03689095  1.21592254 -0.13058309 -1.91792801] 1.0 False
[ 0.0612094   1.41218524 -0.16894165 -2.24809805] 1.0 False
[ 0.08945311  1.21901088 -0.21390361 -2.01189468] 1.0 True
Reward for this episode was: 12.0
[-0.04897552 -0.16105955  0.02408328  0.34656504] 1.0 False
[-0.05219671  0.0337117   0.03101458  0.06157268] 1.0 False
[-0.05152248

[ 0.14709757  0.16198954 -0.19653681 -0.59887917] 1.0 False
[ 0.15033736  0.35923941 -0.2085144  -0.94646857] 1.0 False
[ 0.15752215  0.1674424  -0.22744377 -0.72586464] 1.0 True
Reward for this episode was: 19.0
[ 0.03462758 -0.20703638 -0.01081778  0.24421627] 1.0 False
[ 0.03048685 -0.0117616  -0.00593346 -0.05185913] 1.0 False
[ 0.03025162 -0.20679797 -0.00697064  0.23894585] 1.0 False
[ 0.02611566 -0.01157713 -0.00219173 -0.05592764] 1.0 False
[ 0.02588412  0.18357617 -0.00331028 -0.34930127] 1.0 False
[ 0.02955564  0.37874505 -0.0102963  -0.6430262 ] 1.0 False
[ 0.03713054  0.57400898 -0.02315683 -0.93893364] 1.0 False
[ 0.04861072  0.37920674 -0.0419355  -0.65361612] 1.0 False
[ 0.05619486  0.18469305 -0.05500782 -0.37442751] 1.0 False
[ 0.05988872 -0.00960615 -0.06249637 -0.09958369] 1.0 False
[ 0.0596966   0.18635323 -0.06448805 -0.41131088] 1.0 False
[ 0.06342366 -0.00779807 -0.07271426 -0.13963563] 1.0 False
[ 0.0632677   0.18828593 -0.07550698 -0.45434356] 1.0 False
[ 0.067